name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建并推送后端 Docker 镜像
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auto-quiz-backend:latest
          build-args: |
            API_KEY=${{ secrets.API_KEY }}
            API_URL=${{ secrets.API_URL }}
            MODEL=${{ secrets.MODEL }}
            ENVIRONMENT=production

      # 配置前端环境变量
      - name: Create frontend env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.PRODUCTION_API_URL }}" > frontend/.env

      # 创建 nginx.conf 文件并放入 frontend 目录
      - name: Create nginx.conf
        run: |
          cat > frontend/nginx.conf << 'EOF'
          server {
              listen 80;
              
              location / {
                  root /usr/share/nginx/html;
                  index index.html index.htm;
                  try_files $uri $uri/ /index.html;
              }
              
              location /api/ {
                  proxy_pass http://backend:5000/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }

              # 静态资源缓存配置
              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                  expires 30d;
                  add_header Cache-Control "public, no-transform";
              }

              # 安全相关头部
              add_header X-Content-Type-Options nosniff;
              add_header X-Frame-Options DENY;
              add_header X-XSS-Protection "1; mode=block";

              error_page 404 /index.html;
              error_page 500 502 503 504 /50x.html;
              location = /50x.html {
                  root /usr/share/nginx/html;
              }
          }
          EOF

      # 复制 Dockerfile.frontend 到前端目录内
      - name: Copy Dockerfile to frontend directory
        run: cp Dockerfile.frontend frontend/

      # 设置 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # 安装并构建前端
      - name: Install and build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # 构建并推送前端 Docker 镜像
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auto-quiz-frontend:latest

      # 使用 SSH 部署到服务器
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # 打印调试信息
            echo "Starting deployment..."
            echo "Current directory: $(pwd)"
            
            # 创建应用目录
            mkdir -p /opt/auto_quiz
            cd /opt/auto_quiz
            echo "Created and changed to directory: $(pwd)"
            
            # 检查 Docker 是否安装
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
            fi
            
            # 检查 Docker Compose 是否安装
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found. Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
            fi
            
            # 创建单独的变量来存储 Docker Hub 用户名
            DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
            
            # 创建 docker-compose.yml 文件 - 注意这里不使用 EOL 重定向，而是逐行写入文件
            echo "Creating docker-compose.yml..."
            rm -f docker-compose.yml
            echo "version: '3'" > docker-compose.yml
            echo "" >> docker-compose.yml
            echo "services:" >> docker-compose.yml
            echo "  backend:" >> docker-compose.yml
            echo "    image: $DOCKER_USERNAME/auto-quiz-backend:latest" >> docker-compose.yml
            echo "    restart: unless-stopped" >> docker-compose.yml
            echo "    environment:" >> docker-compose.yml
            echo "      - API_KEY=${{ secrets.API_KEY }}" >> docker-compose.yml
            echo "      - API_URL=${{ secrets.API_URL }}" >> docker-compose.yml
            echo "      - MODEL=${{ secrets.MODEL }}" >> docker-compose.yml
            echo "      - ENVIRONMENT=production" >> docker-compose.yml
            echo "    volumes:" >> docker-compose.yml
            echo "      - quiz_data:/data" >> docker-compose.yml
            echo "    networks:" >> docker-compose.yml
            echo "      - auto_quiz_network" >> docker-compose.yml
            echo "" >> docker-compose.yml
            echo "  frontend:" >> docker-compose.yml
            echo "    image: $DOCKER_USERNAME/auto-quiz-frontend:latest" >> docker-compose.yml
            echo "    restart: unless-stopped" >> docker-compose.yml
            echo "    ports:" >> docker-compose.yml
            echo "      - \"80:80\"" >> docker-compose.yml
            echo "    depends_on:" >> docker-compose.yml
            echo "      - backend" >> docker-compose.yml
            echo "    networks:" >> docker-compose.yml
            echo "      - auto_quiz_network" >> docker-compose.yml
            echo "" >> docker-compose.yml
            echo "networks:" >> docker-compose.yml
            echo "  auto_quiz_network:" >> docker-compose.yml
            echo "" >> docker-compose.yml
            echo "volumes:" >> docker-compose.yml
            echo "  quiz_data:" >> docker-compose.yml
            
            echo "Content of docker-compose.yml:"
            cat docker-compose.yml
            
            # 尝试使用不同的 Docker Compose 命令
            echo "Checking Docker Compose version:"
            docker-compose --version || docker compose --version || echo "Docker Compose version command failed"
            
            echo "Pulling latest images..."
            docker-compose pull || docker compose pull || sudo docker-compose pull || sudo docker compose pull || echo "Failed to pull images"
            
            echo "Stopping any running containers..."
            docker-compose down || docker compose down || sudo docker-compose down || sudo docker compose down || echo "Failed to stop containers (might be none running)"
            
            echo "Starting containers..."
            docker-compose up -d || docker compose up -d || sudo docker-compose up -d || sudo docker compose up -d || echo "Failed to start containers"
            
            echo "Container status:"
            docker-compose ps || docker compose ps || sudo docker-compose ps || sudo docker compose ps || echo "Failed to show container status"
            
            echo "Deployment script completed"